spring:
  application:
    name: final_project_712
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_admin
    password: 12345678
    url: jdbc:mysql://192.168.1.102:3306/db_712?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    hikari:
      pool-name: HikariCP
      idle-timeout: 600000
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
  mail:
    username: newtestemail321@163.com
    host: smtp.163.com
    password: XSisH3AwMJu6Nc93
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  logging:
    level:
      root: INFO
      org.springframework.web: WARN
      com.example.yourpackage: DEBUG
    file:
      name: myapplog.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  data:
    redis:
      host: 192.168.1.102
      port: 6379
      username: user712
      password: password
server:
  port: 8082
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: _712.final_project_712.controller
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: _712.final_project_712.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 项目文档
      locations: classpath:docs/*
  basic:
    enable: false
jwt:
  secret: qwdcvefwe212wsasawwfaws
  expire: 30
  issuer: zzzlm
headImgPath: "d:/images/headImg"

