spring:
  application:
    name: final_project_712
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_admin
    password: 12345678
    url: jdbc:mysql://192.168.1.102:3306/db_712?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    hikari:
      pool-name: HikariCP
      idle-timeout: 600000
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
  mail:
    username: wenshuntao@qq.com
    host: smtp.qq.com
    password: kkk
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  logging:
    level:
      root: INFO
      org.springframework.web: WARN
      com.example.yourpackage: DEBUG
    file:
      name: myapplog.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  data:
    redis:
      host: 192.168.100.1
      port: 6379
      username: user712
      password: password
server:
  port: 8082
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '后台管理'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.controller.admin
    - group: '前台'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.controller.user
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
jwt:
  secret: qwdcvefwe212wsasawwfaws
  expire: 30
  issuer: zzzlm
headImgPath: "d:/images/headImg"

